name: Deploy FreqTrade Bot

on:
  push:
    branches: [main, master, stable]
  pull_request:
    branches: [main, master, stable]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file with secrets
        run: |
          cat > .env << EOL
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          EXCHANGE_KEY=${{ secrets.EXCHANGE_KEY }}
          EXCHANGE_SECRET=${{ secrets.EXCHANGE_SECRET }}
          FREQTRADE_STRATEGY=${{ secrets.FREQTRADE_STRATEGY || 'HarmonicDivergence' }}
          EOL

      - name: Create secure config for production
        run: |
          # Create a version of the config with redacted API keys
          cat user_data/config.json | jq '.exchange.key = "" | .exchange.secret = "" | .telegram.token = "" | .telegram.chat_id = ""' > user_data/config.secure.json
          mv user_data/config.secure.json user_data/config.json

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Create necessary directories on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "mkdir -p ~/freqtrade/scripts ~/freqtrade/user_data"

      - name: Deploy to server
        run: |
          scp docker-compose.prod.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/freqtrade/
          scp -r user_data/* ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/freqtrade/user_data/
          scp .env ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/freqtrade/
          scp scripts/deploy_freqtrade.sh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/freqtrade/scripts/
          scp scripts/monitor_freqtrade.sh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/freqtrade/scripts/
          scp scripts/prepare_server.sh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/freqtrade/scripts/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "chmod +x ~/freqtrade/scripts/*.sh"

      - name: Run server preparation script
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd ~/freqtrade && scripts/prepare_server.sh"

      - name: Run deployment script on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd ~/freqtrade && scripts/deploy_freqtrade.sh"

      - name: Verify deployment
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd ~/freqtrade && docker-compose -f docker-compose.prod.yml ps"

      - name: Setup monitoring cron job
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '(crontab -l 2>/dev/null || echo "") | grep -v "monitor_freqtrade.sh" | { cat; echo "*/15 * * * * $HOME/freqtrade/scripts/monitor_freqtrade.sh >> /dev/null 2>&1"; } | crontab -'
